package Instrument_gui;

import Cartridge_pkg.Cartridge;
import Instrument_pkg.Instrument;
import TestInstance_pkg.TestInstance;
import JDBCqueries_pkg.JDBCqueries;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.io.*;

/**
 *
 * @author David Kloosterman
 */
public class TopScreen extends javax.swing.JFrame {

    public static final String TESTFILE_SAMPLE = ".\\TestImage.tif";

    TestInstance test;
    Cartridge cartridge;
    Instrument instrument;

    /**
     * Creates new form TopScreen
     */
    public TopScreen() {
        initComponents();
        String display = null;

        try {
            this.instrument = new Instrument();

            InfoPanel.setVisible(false);
            CartridgeInfoButton.setVisible(false);
            EndTestButton.setVisible(false);
            DisplayTestButton.setVisible(false);

            // load combobox with all instr IDs
            ArrayList<String> allInstrIDs = new ArrayList<String>();
            JDBCqueries queries = new JDBCqueries();

            SelectComboBox.removeAllItems();
            allInstrIDs = queries.getAllInstrumentIDs();
            for (String ID : allInstrIDs) {
                SelectComboBox.addItem(ID);
            }

        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoPanel = new javax.swing.JPanel();
        CloseInfoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();
        SelectComboBox = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        EndTestButton = new javax.swing.JButton();
        DisplayTestButton = new javax.swing.JButton();
        InstrumentInfoButton = new javax.swing.JButton();
        InsertCartridgeButton = new javax.swing.JButton();
        CartridgeInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SensoDx Topscreen");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));

        InfoPanel.setBackground(new java.awt.Color(204, 204, 255));
        InfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CloseInfoButton.setText("Close");
        CloseInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseInfoButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        InfoTextArea.setColumns(20);
        InfoTextArea.setRows(5);
        InfoTextArea.setText("Information");
        jScrollPane1.setViewportView(InfoTextArea);

        SelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectComboBoxActionPerformed(evt);
            }
        });

        EndTestButton.setText("End Test");
        EndTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndTestButtonActionPerformed(evt);
            }
        });

        DisplayTestButton.setText("Display Test");
        DisplayTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(SelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayTestButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EndTestButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseInfoButton)))
                .addContainerGap())
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseInfoButton)
                    .addComponent(SelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndTestButton)
                    .addComponent(DisplayTestButton))
                .addContainerGap())
        );

        InstrumentInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Instrument_gui/Instrument.png"))); // NOI18N
        InstrumentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrumentInfoButtonActionPerformed(evt);
            }
        });

        InsertCartridgeButton.setBackground(new java.awt.Color(255, 255, 153));
        InsertCartridgeButton.setText("Press here to simulate inserting a cartridge");
        InsertCartridgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertCartridgeButtonActionPerformed(evt);
            }
        });

        CartridgeInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Instrument_gui/Cartridge.png"))); // NOI18N
        CartridgeInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartridgeInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(InsertCartridgeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CartridgeInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InstrumentInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CartridgeInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InstrumentInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsertCartridgeButton))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseInfoButtonActionPerformed

        InfoPanel.setVisible(false);
    }//GEN-LAST:event_CloseInfoButtonActionPerformed

    private void InstrumentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrumentInfoButtonActionPerformed

        try {
            JDBCqueries queries = new JDBCqueries();

            queries.getInstrumentMfgInfo((String) SelectComboBox.getSelectedItem(), this.instrument);
            queries.getInstrumentDeploymentInfo((String) SelectComboBox.getSelectedItem(), this.instrument);

            InfoTextArea.setText(this.instrument.toString());

            // Make Instrument Info Panel visible
            SelectComboBox.setVisible(true);
            InfoPanel.setVisible(true);
        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally
    }//GEN-LAST:event_InstrumentInfoButtonActionPerformed

    private void SelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectComboBoxActionPerformed

         try {
            this.instrument = null;
            this.instrument = new Instrument();

            // update Instrument Info Text Area with selected Instrument ID
            JDBCqueries queries = new JDBCqueries();
            queries.getInstrumentMfgInfo((String) SelectComboBox.getSelectedItem(), this.instrument);
            queries.getInstrumentDeploymentInfo((String) SelectComboBox.getSelectedItem(), this.instrument);
            InfoTextArea.setText(this.instrument.toString());

        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally 
    }//GEN-LAST:event_SelectComboBoxActionPerformed

    private void InsertCartridgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertCartridgeButtonActionPerformed
 
        try {
            this.test = new TestInstance();
            this.cartridge = new Cartridge();

            // temp code until real cartridges exist
            this.createTestCartridge(this.cartridge);

            // update Instrument Info Text Area with selected Instrument ID
            JDBCqueries queries = new JDBCqueries();
            queries.insertCartridge(this.cartridge);
            queries.getCartridgeMfgInfo(this.cartridge);

            File f = new File(TESTFILE_SAMPLE);
            if (f.exists() && !f.isDirectory()) {
                //             temp sample clinical test file
                this.test.dicom.setClinicalTestFilePathInInstrument(TESTFILE_SAMPLE);

                if (test.processTest(this.instrument, this.cartridge)) {
                    InfoTextArea.setText(this.test.getTestResultString() + "\n\n" + this.test.toString());
                } else {
                    InfoTextArea.setText(this.test.getTestResultString());
                }

            }

            // update view
            CartridgeInfoButton.setVisible(true);
            SelectComboBox.setVisible(false);
            InsertCartridgeButton.setVisible(false);
            InfoPanel.setVisible(true);
            EndTestButton.setVisible(true);
            DisplayTestButton.setVisible(true);
        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally 
    }//GEN-LAST:event_InsertCartridgeButtonActionPerformed

    public void createTestCartridge(Cartridge cartridge) {

        try {
            // temp code : create a cartridge ID from the current timestamp
            /*
            (cartridge_id, manufactured_timestamp, manufactured_location, assay_type,
                             subsystem_1_id, subsystem_2_id, subsystem_3_id)
             */
            Timestamp timestamp = new Timestamp(System.currentTimeMillis());
            String cartID = timestamp.toString();

            cartID = cartID.replace(" ", "");
            cartID = cartID.replace(":", "");
            cartID = cartID.replace(".", "");
            cartID = cartID.replace("-", "");
            cartridge.setCartridge_id(cartID);
            cartridge.setManufactured_timestamp(new Timestamp(System.currentTimeMillis()));
            cartridge.setManufactured_location("Perinton, NY");
            cartridge.setAssay_type(test.CARDIAC_WELLNESS_TEST);
            cartridge.setSubsystem_1_id("0000000010000002");
            cartridge.setSubsystem_2_id("0000000020000002");
            cartridge.setSubsystem_3_id("0000000030000002");

        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally try
    }


    private void CartridgeInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartridgeInfoButtonActionPerformed

        try {
            JDBCqueries queries = new JDBCqueries();
            queries.getCartridgeMfgInfo(this.cartridge);
            InfoTextArea.setText(this.cartridge.toString());

            // Make Instrument Info Panel visible
            SelectComboBox.setVisible(false);
            InfoPanel.setVisible(true);
        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally     
    }//GEN-LAST:event_CartridgeInfoButtonActionPerformed

    private void EndTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndTestButtonActionPerformed
        InfoPanel.setVisible(false);
        InsertCartridgeButton.setVisible(true);
        CartridgeInfoButton.setVisible(false);
        EndTestButton.setVisible(false);
        DisplayTestButton.setVisible(false);
        this.test = null;
        this.cartridge = null;
    }//GEN-LAST:event_EndTestButtonActionPerformed

    private void DisplayTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTestButtonActionPerformed
        InfoTextArea.setText(this.test.toString());
    }//GEN-LAST:event_DisplayTestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new TopScreen().setVisible(true);
            }
        });

    } // end main


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartridgeInfoButton;
    private javax.swing.JButton CloseInfoButton;
    private javax.swing.JButton DisplayTestButton;
    private javax.swing.JButton EndTestButton;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextArea InfoTextArea;
    private javax.swing.JButton InsertCartridgeButton;
    private javax.swing.JButton InstrumentInfoButton;
    private javax.swing.JComboBox<String> SelectComboBox;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
